apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: springboot-app-dev
  labels:
    app: springboot-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app-container
        image: 905418280053.dkr.ecr.us-east-1.amazonaws.com/eks-repo:V001
        ports:
        - containerPort: 80
