apiVersion: v1
kind: Service
metadata:
  name: mv-app
  namespace: mv-app-dev
  labels:
    app: mv-app
spec:
  type: LoadBalancer
  selector:
    app: mv-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
