apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  namespace: springboot-app-dev
  labels:
    app: springboot-app
spec:
  type: LoadBalancer
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
